# Generated by Django 4.2.7 on 2024-03-11 12:51

from django.db import migrations, models
import django.db.models.deletion
import sync_model.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawStockAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=32)),
                ('action_type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell'), ('cancel', 'cancel')], max_length=10)),
                ('update_datetime', models.DateTimeField()),
                ('canceled', models.BooleanField()),
                ('stock_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StockAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_method', models.TextField()),
                ('batch_size', models.IntegerField(default=100)),
                ('order_by', models.JSONField(default=sync_model.models.default_order_by)),
                ('last_sync', models.JSONField(default=dict)),
                ('filter_by', models.JSONField(default=dict)),
                ('dependencies', models.ManyToManyField(to='sync_model.synctask')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
            ],
        ),
    ]
