# Generated by Django 5.0.2 on 2024-03-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctask',
            name='source_db',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='synctask',
            name='target_db',
            field=models.TextField(default='default'),
        ),
    ]
