# Generated by Django 5.0.2 on 2024-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synctask',
            name='dependencies',
            field=models.ManyToManyField(to='sync_model.synctask'),
        ),
    ]
