# Generated by Django 5.0.2 on 2024-03-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_model', '0004_stockaction_stock_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaction',
            name='sender',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
